# Generated by Django 3.0.6 on 2020-05-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=100)),
                ('instu', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=15)),
                ('chk_in_time', models.CharField(max_length=20)),
                ('chk_out_time', models.CharField(max_length=20)),
                ('img_name', models.CharField(max_length=50)),
            ],
        ),
    ]
