# Generated by Django 3.0.6 on 2020-05-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('io_handlr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='visitors',
            new_name='Vsitors',
        ),
    ]
