# Generated by Django 3.0.6 on 2020-05-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('io_handlr', '0002_auto_20200527_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vsitors',
            new_name='Visitors',
        ),
    ]
