# Generated by Django 3.0.6 on 2020-05-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('io_handlr', '0003_auto_20200527_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitors',
            new_name='Visitor',
        ),
    ]
